// LangLab 字庫 — 依日常使用頻率排序（前面的優先學習）
// 日文格式: [單字, 羅馬拼音, 中譯, 例句, 例句羅馬拼音, 例句中譯, 等級]
// 英文格式: [單字, 音標, 中譯, 例句, 例句中譯, 等級]
// 直接在陣列中追加即可擴充字庫。

const WORDS_JP = [
["ありがとう","arigatou","謝謝","手伝ってくれてありがとう。","tetsudatte kurete arigatou.","謝謝你幫我。","N5"],
["おはよう","ohayou","早安","おはよう、よく寝られた？","ohayou, yoku nerareta?","早安，睡得好嗎？","N5"],
["こんにちは","konnichiwa","你好（白天）","こんにちは、お元気ですか。","konnichiwa, ogenki desu ka.","你好，最近好嗎？","N5"],
["こんばんは","konbanwa","晚上好","こんばんは、今日は寒いですね。","konbanwa, kyou wa samui desu ne.","晚上好，今天好冷呢。","N5"],
["すみません","sumimasen","不好意思；對不起","すみません、駅はどこですか。","sumimasen, eki wa doko desu ka.","不好意思，車站在哪裡？","N5"],
["ごめんなさい","gomennasai","對不起","遅れてごめんなさい。","okurete gomennasai.","對不起我遲到了。","N5"],
["お願いします","onegai shimasu","麻煩了；拜託","水をお願いします。","mizu o onegai shimasu.","麻煩給我水。","N5"],
["はい","hai","是；好","はい、わかりました。","hai, wakarimashita.","好的，我明白了。","N5"],
["いいえ","iie","不；不是","いいえ、違います。","iie, chigaimasu.","不，不是的。","N5"],
["さようなら","sayounara","再見","さようなら、また会いましょう。","sayounara, mata aimashou.","再見，後會有期。","N5"],
["また明日","mata ashita","明天見","じゃあ、また明日！","jaa, mata ashita!","那麼，明天見！","N5"],
["おやすみなさい","oyasuminasai","晚安","もう寝るね、おやすみなさい。","mou neru ne, oyasuminasai.","我要睡了，晚安。","N5"],
["いただきます","itadakimasu","開動了","おいしそう！いただきます。","oishisou! itadakimasu.","看起來好好吃！開動了。","N5"],
["ごちそうさま","gochisousama","多謝款待","ごちそうさま、おいしかったです。","gochisousama, oishikatta desu.","多謝款待，很好吃。","N5"],
["大丈夫","daijoubu","沒關係；沒問題","大丈夫ですか。","daijoubu desu ka.","你還好嗎？","N5"],
["私","watashi","我","私は学生です。","watashi wa gakusei desu.","我是學生。","N5"],
["あなた","anata","你","あなたの名前は何ですか。","anata no namae wa nan desu ka.","你叫什麼名字？","N5"],
["名前","namae","名字","お名前を教えてください。","onamae o oshiete kudasai.","請告訴我你的名字。","N5"],
["今日","kyou","今天","今日はいい天気ですね。","kyou wa ii tenki desu ne.","今天天氣真好呢。","N5"],
["明日","ashita","明天","明日は休みです。","ashita wa yasumi desu.","明天放假。","N5"],
["昨日","kinou","昨天","昨日は忙しかったです。","kinou wa isogashikatta desu.","昨天很忙。","N5"],
["今","ima","現在","今、何時ですか。","ima, nanji desu ka.","現在幾點？","N5"],
["時間","jikan","時間","時間がありません。","jikan ga arimasen.","沒有時間了。","N5"],
["食べる","taberu","吃","朝ごはんを食べる。","asagohan o taberu.","吃早餐。","N5"],
["飲む","nomu","喝","コーヒーを飲みます。","koohii o nomimasu.","喝咖啡。","N5"],
["行く","iku","去","学校へ行きます。","gakkou e ikimasu.","去學校。","N5"],
["来る","kuru","來","友達が家に来ます。","tomodachi ga ie ni kimasu.","朋友要來我家。","N5"],
["帰る","kaeru","回去；回家","もう帰りたいです。","mou kaeritai desu.","我想回家了。","N5"],
["見る","miru","看","映画を見ました。","eiga o mimashita.","看了電影。","N5"],
["聞く","kiku","聽；問","音楽を聞きます。","ongaku o kikimasu.","聽音樂。","N5"],
["話す","hanasu","說話","日本語を話せますか。","nihongo o hanasemasu ka.","你會說日語嗎？","N5"],
["買う","kau","買","パンを買いました。","pan o kaimashita.","買了麵包。","N5"],
["水","mizu","水","水を一杯ください。","mizu o ippai kudasai.","請給我一杯水。","N5"],
["ごはん","gohan","飯；餐","晩ごはんは何にする？","bangohan wa nani ni suru?","晚餐要吃什麼？","N5"],
["お金","okane","錢","お金が足りない。","okane ga tarinai.","錢不夠。","N5"],
["家","ie","家","家でゆっくりします。","ie de yukkuri shimasu.","在家好好休息。","N5"],
["学校","gakkou","學校","学校は九時からです。","gakkou wa kuji kara desu.","學校九點開始。","N5"],
["会社","kaisha","公司","会社まで電車で行きます。","kaisha made densha de ikimasu.","搭電車去公司。","N5"],
["駅","eki","車站","駅で待っています。","eki de matte imasu.","我在車站等你。","N5"],
["電車","densha","電車","電車が来ました。","densha ga kimashita.","電車來了。","N5"],
["好き","suki","喜歡","日本料理が好きです。","nihon ryouri ga suki desu.","我喜歡日本料理。","N5"],
["嫌い","kirai","討厭","野菜が嫌いです。","yasai ga kirai desu.","我討厭蔬菜。","N5"],
["おいしい","oishii","好吃","このラーメンはおいしい！","kono raamen wa oishii!","這碗拉麵好好吃！","N5"],
["高い","takai","貴；高","この店は少し高いです。","kono mise wa sukoshi takai desu.","這家店有點貴。","N5"],
["安い","yasui","便宜","もっと安いのはありますか。","motto yasui no wa arimasu ka.","有更便宜的嗎？","N5"],
["大きい","ookii","大的","もっと大きいサイズをください。","motto ookii saizu o kudasai.","請給我大一點的尺寸。","N5"],
["小さい","chiisai","小的","この靴は小さすぎます。","kono kutsu wa chiisasugimasu.","這雙鞋太小了。","N5"],
["新しい","atarashii","新的","新しい携帯を買いたい。","atarashii keitai o kaitai.","想買新手機。","N5"],
["暑い","atsui","熱（天氣）","今日はとても暑いですね。","kyou wa totemo atsui desu ne.","今天好熱啊。","N5"],
["寒い","samui","冷","冬は寒いのが苦手です。","fuyu wa samui no ga nigate desu.","我怕冬天的冷。","N5"],
["忙しい","isogashii","忙碌","最近仕事が忙しいです。","saikin shigoto ga isogashii desu.","最近工作很忙。","N5"],
["楽しい","tanoshii","開心；有趣","旅行はとても楽しかった。","ryokou wa totemo tanoshikatta.","旅行非常開心。","N5"],
["いくら","ikura","多少錢","これはいくらですか。","kore wa ikura desu ka.","這個多少錢？","N5"],
["どこ","doko","哪裡","トイレはどこですか。","toire wa doko desu ka.","廁所在哪裡？","N5"],
["いつ","itsu","什麼時候","いつ日本に来ましたか。","itsu nihon ni kimashita ka.","你什麼時候來日本的？","N5"],
["何","nani","什麼","これは何ですか。","kore wa nan desu ka.","這是什麼？","N5"],
["誰","dare","誰","あの人は誰ですか。","ano hito wa dare desu ka.","那個人是誰？","N5"],
["どうして","doushite","為什麼","どうして遅れたんですか。","doushite okuretan desu ka.","為什麼遲到了？","N5"],
["ください","kudasai","請給我","これをください。","kore o kudasai.","請給我這個。","N5"],
["わかる","wakaru","懂；明白","意味がわかりません。","imi ga wakarimasen.","我不懂意思。","N5"],
["朝","asa","早上","朝は七時に起きます。","asa wa shichiji ni okimasu.","早上七點起床。","N5"],
["夜","yoru","晚上","夜は何をしますか。","yoru wa nani o shimasu ka.","晚上要做什麼？","N5"],
["昼","hiru","中午；白天","昼にラーメンを食べた。","hiru ni raamen o tabeta.","中午吃了拉麵。","N5"],
["週末","shuumatsu","週末","週末は何か予定ある？","shuumatsu wa nanika yotei aru?","週末有什麼計畫嗎？","N4"],
["毎日","mainichi","每天","毎日日本語を勉強します。","mainichi nihongo o benkyou shimasu.","每天學日語。","N5"],
["起きる","okiru","起床","朝早く起きるのは大変だ。","asa hayaku okiru no wa taihen da.","早起很辛苦。","N5"],
["寝る","neru","睡覺","昨日は十二時に寝ました。","kinou wa juuniji ni nemashita.","昨天十二點睡的。","N5"],
["働く","hataraku","工作","銀行で働いています。","ginkou de hataraite imasu.","我在銀行工作。","N5"],
["休む","yasumu","休息；請假","今日は会社を休みます。","kyou wa kaisha o yasumimasu.","今天向公司請假。","N5"],
["勉強する","benkyou suru","學習","図書館で勉強します。","toshokan de benkyou shimasu.","在圖書館唸書。","N5"],
["使う","tsukau","使用","この机を使ってもいいですか。","kono tsukue o tsukatte mo ii desu ka.","可以用這張桌子嗎？","N5"],
["作る","tsukuru","做；製作","晩ごはんを作ります。","bangohan o tsukurimasu.","做晚餐。","N5"],
["待つ","matsu","等待","ここで待っていてください。","koko de matte ite kudasai.","請在這裡等。","N5"],
["会う","au","見面","明日友達に会います。","ashita tomodachi ni aimasu.","明天要和朋友見面。","N5"],
["電話","denwa","電話","後で電話します。","ato de denwa shimasu.","待會打電話給你。","N5"],
["携帯","keitai","手機","携帯を忘れました。","keitai o wasuremashita.","我忘了帶手機。","N4"],
["友達","tomodachi","朋友","友達と遊びに行く。","tomodachi to asobi ni iku.","和朋友出去玩。","N5"],
["家族","kazoku","家人","家族は四人です。","kazoku wa yonin desu.","我家有四個人。","N5"],
["仕事","shigoto","工作","仕事が終わりました。","shigoto ga owarimashita.","工作結束了。","N5"],
["天気","tenki","天氣","明日の天気はどうですか。","ashita no tenki wa dou desu ka.","明天天氣如何？","N5"],
["雨","ame","雨","午後から雨が降るそうです。","gogo kara ame ga furu sou desu.","聽說下午會下雨。","N5"],
["元気","genki","有精神；健康","お元気ですか。","ogenki desu ka.","你好嗎？","N5"],
["病院","byouin","醫院","頭が痛いので病院へ行きます。","atama ga itai node byouin e ikimasu.","頭痛所以要去醫院。","N5"],
["薬","kusuri","藥","食後に薬を飲んでください。","shokugo ni kusuri o nonde kudasai.","請飯後吃藥。","N5"],
["痛い","itai","痛","お腹が痛いです。","onaka ga itai desu.","肚子痛。","N5"],
["疲れる","tsukareru","疲累","今日はとても疲れた。","kyou wa totemo tsukareta.","今天好累。","N4"],
["お腹が空く","onaka ga suku","肚子餓","お腹が空きました。","onaka ga sukimashita.","肚子餓了。","N5"],
["喉が渇く","nodo ga kawaku","口渴","喉が渇いたので水を飲む。","nodo ga kawaita node mizu o nomu.","口渴了所以喝水。","N4"],
["店","mise","商店","あの店は人気があります。","ano mise wa ninki ga arimasu.","那家店很受歡迎。","N5"],
["コンビニ","konbini","便利商店","コンビニでお弁当を買った。","konbini de obentou o katta.","在便利商店買了便當。","N5"],
["スーパー","suupaa","超市","スーパーは駅の近くにあります。","suupaa wa eki no chikaku ni arimasu.","超市在車站附近。","N5"],
["レストラン","resutoran","餐廳","このレストランは予約が必要です。","kono resutoran wa yoyaku ga hitsuyou desu.","這間餐廳需要預約。","N5"],
["メニュー","menyuu","菜單","メニューを見せてください。","menyuu o misete kudasai.","請給我看菜單。","N5"],
["注文","chuumon","點餐；訂購","注文をお願いします。","chuumon o onegai shimasu.","我要點餐。","N4"],
["予約","yoyaku","預約","七時に予約したいです。","shichiji ni yoyaku shitai desu.","我想預約七點。","N4"],
["会計","kaikei","結帳","お会計をお願いします。","okaikei o onegai shimasu.","麻煩結帳。","N4"],
["現金","genkin","現金","現金しか使えません。","genkin shika tsukaemasen.","只能用現金。","N4"],
["カード","kaado","卡片；信用卡","カードで払えますか。","kaado de haraemasu ka.","可以刷卡嗎？","N5"],
["お茶","ocha","茶","お茶をどうぞ。","ocha o douzo.","請喝茶。","N5"],
["コーヒー","koohii","咖啡","コーヒーを二つください。","koohii o futatsu kudasai.","請給我兩杯咖啡。","N5"],
["牛乳","gyuunyuu","牛奶","毎朝牛乳を飲みます。","maiasa gyuunyuu o nomimasu.","每天早上喝牛奶。","N5"],
["卵","tamago","蛋","卵を三つ買ってきて。","tamago o mittsu katte kite.","幫我買三顆蛋回來。","N5"],
["肉","niku","肉","肉より魚のほうが好きです。","niku yori sakana no hou ga suki desu.","比起肉我更喜歡魚。","N5"],
["魚","sakana","魚","この魚は新鮮ですね。","kono sakana wa shinsen desu ne.","這魚很新鮮呢。","N5"],
["野菜","yasai","蔬菜","野菜をもっと食べたほうがいい。","yasai o motto tabeta hou ga ii.","最好多吃點蔬菜。","N5"],
["果物","kudamono","水果","デザートに果物を食べる。","dezaato ni kudamono o taberu.","甜點吃水果。","N5"],
["朝ごはん","asagohan","早餐","朝ごはんを食べましたか。","asagohan o tabemashita ka.","吃早餐了嗎？","N5"],
["お弁当","obentou","便當","お昼はお弁当を持ってきた。","ohiru wa obentou o motte kita.","中午帶了便當來。","N5"],
["部屋","heya","房間","部屋を掃除しました。","heya o souji shimashita.","打掃了房間。","N5"],
["トイレ","toire","廁所","トイレを借りてもいいですか。","toire o karite mo ii desu ka.","可以借用廁所嗎？","N5"],
["お風呂","ofuro","浴室；泡澡","お風呂に入ってから寝ます。","ofuro ni haitte kara nemasu.","泡完澡再睡。","N5"],
["ドア","doa","門","ドアを閉めてください。","doa o shimete kudasai.","請關門。","N5"],
["窓","mado","窗戶","窓を開けてもいいですか。","mado o akete mo ii desu ka.","可以開窗嗎？","N5"],
["椅子","isu","椅子","この椅子に座ってください。","kono isu ni suwatte kudasai.","請坐這張椅子。","N5"],
["机","tsukue","桌子","机の上に本があります。","tsukue no ue ni hon ga arimasu.","桌上有書。","N5"],
["本","hon","書","週末に本を読みます。","shuumatsu ni hon o yomimasu.","週末讀書。","N5"],
["読む","yomu","閱讀","毎晩ニュースを読みます。","maiban nyuusu o yomimasu.","每晚看新聞。","N5"],
["書く","kaku","寫","名前をここに書いてください。","namae o koko ni kaite kudasai.","請把名字寫在這裡。","N5"],
["教える","oshieru","教；告訴","道を教えてください。","michi o oshiete kudasai.","請告訴我怎麼走。","N5"],
["覚える","oboeru","記住","単語を覚えるのが難しい。","tango o oboeru no ga muzukashii.","背單字很難。","N4"],
["忘れる","wasureru","忘記","傘を忘れないでね。","kasa o wasurenaide ne.","別忘了帶傘喔。","N5"],
["知る","shiru","知道","その話は知りませんでした。","sono hanashi wa shirimasen deshita.","我不知道那件事。","N5"],
["思う","omou","覺得；想","それはいいと思います。","sore wa ii to omoimasu.","我覺得那樣很好。","N4"],
["言う","iu","說","もう一度言ってください。","mou ichido itte kudasai.","請再說一次。","N5"],
["ゆっくり","yukkuri","慢慢地","もっとゆっくり話してください。","motto yukkuri hanashite kudasai.","請說慢一點。","N5"],
["もう一度","mou ichido","再一次","もう一度お願いします。","mou ichido onegai shimasu.","麻煩再一次。","N5"],
["たくさん","takusan","很多","人がたくさんいますね。","hito ga takusan imasu ne.","人好多啊。","N5"],
["少し","sukoshi","一點點","日本語が少し話せます。","nihongo ga sukoshi hanasemasu.","我會說一點日語。","N5"],
["とても","totemo","非常","この映画はとても面白い。","kono eiga wa totemo omoshiroi.","這部電影非常有趣。","N5"],
["たぶん","tabun","大概；也許","たぶん明日は晴れるでしょう。","tabun ashita wa hareru deshou.","明天大概會放晴吧。","N4"],
["いつも","itsumo","總是","いつもありがとうございます。","itsumo arigatou gozaimasu.","一直以來謝謝你。","N5"],
["時々","tokidoki","有時","時々映画を見に行きます。","tokidoki eiga o mi ni ikimasu.","有時會去看電影。","N5"],
["初めて","hajimete","第一次","日本は初めてですか。","nihon wa hajimete desu ka.","是第一次來日本嗎？","N5"],
["一緒に","issho ni","一起","一緒に行きましょう。","issho ni ikimashou.","一起去吧。","N5"],
["だから","dakara","所以","雨だから、家にいます。","ame dakara, ie ni imasu.","因為下雨，所以待在家。","N4"],
["でも","demo","但是","行きたい。でも、時間がない。","ikitai. demo, jikan ga nai.","想去，但是沒時間。","N5"],
["右","migi","右邊","次の角を右に曲がってください。","tsugi no kado o migi ni magatte kudasai.","請在下個轉角右轉。","N5"],
["左","hidari","左邊","銀行は左側にあります。","ginkou wa hidarigawa ni arimasu.","銀行在左手邊。","N5"],
["近く","chikaku","附近","この近くにATMはありますか。","kono chikaku ni ATM wa arimasu ka.","這附近有ATM嗎？","N5"],
["遠い","tooi","遠","駅から少し遠いです。","eki kara sukoshi tooi desu.","離車站有點遠。","N5"],
["まっすぐ","massugu","直走；筆直","この道をまっすぐ行ってください。","kono michi o massugu itte kudasai.","請沿這條路直走。","N5"],
["曲がる","magaru","轉彎","あの信号を左に曲がる。","ano shingou o hidari ni magaru.","在那個紅綠燈左轉。","N5"],
["地図","chizu","地圖","地図を見せてもらえますか。","chizu o misete moraemasu ka.","可以給我看地圖嗎？","N5"],
["切符","kippu","車票","切符を二枚ください。","kippu o nimai kudasai.","請給我兩張票。","N5"],
["飛行機","hikouki","飛機","飛行機は何時に出発しますか。","hikouki wa nanji ni shuppatsu shimasu ka.","飛機幾點起飛？","N5"],
["バス","basu","公車","バスで空港へ行きます。","basu de kuukou e ikimasu.","搭公車去機場。","N5"],
["タクシー","takushii","計程車","タクシーを呼んでください。","takushii o yonde kudasai.","請幫我叫計程車。","N5"],
["空港","kuukou","機場","空港まで一時間かかります。","kuukou made ichijikan kakarimasu.","到機場要一小時。","N4"],
["ホテル","hoteru","飯店","ホテルにチェックインします。","hoteru ni chekkuin shimasu.","到飯店辦入住。","N5"],
["荷物","nimotsu","行李","荷物を預けたいです。","nimotsu o azuketai desu.","我想寄放行李。","N4"],
["写真","shashin","照片","写真を撮ってもいいですか。","shashin o totte mo ii desu ka.","可以拍照嗎？","N5"],
["撮る","toru","拍（照）","写真を撮ってもらえますか。","shashin o totte moraemasu ka.","可以幫我拍照嗎？","N5"],
["旅行","ryokou","旅行","来月、日本へ旅行に行きます。","raigetsu, nihon e ryokou ni ikimasu.","下個月要去日本旅行。","N5"],
["休み","yasumi","休假；休息","次の休みはいつですか。","tsugi no yasumi wa itsu desu ka.","下次休假是什麼時候？","N5"],
["誕生日","tanjoubi","生日","お誕生日おめでとう！","otanjoubi omedetou!","生日快樂！","N5"],
["おめでとう","omedetou","恭喜","合格おめでとうございます。","goukaku omedetou gozaimasu.","恭喜你考上了。","N5"],
["プレゼント","purezento","禮物","誕生日プレゼントを選んでいます。","tanjoubi purezento o erande imasu.","正在挑生日禮物。","N5"],
["音楽","ongaku","音樂","どんな音楽が好きですか。","donna ongaku ga suki desu ka.","你喜歡什麼樣的音樂？","N5"],
["映画","eiga","電影","今晩、映画を見ませんか。","konban, eiga o mimasen ka.","今晚要不要看電影？","N5"],
["ゲーム","geemu","遊戲","弟はゲームばかりしている。","otouto wa geemu bakari shite iru.","弟弟一直在打電動。","N5"],
["運動","undou","運動","健康のために運動しています。","kenkou no tame ni undou shite imasu.","為了健康在運動。","N4"],
["散歩","sanpo","散步","犬と散歩に行きます。","inu to sanpo ni ikimasu.","帶狗去散步。","N5"],
["泳ぐ","oyogu","游泳","夏は海で泳ぎたい。","natsu wa umi de oyogitai.","夏天想去海邊游泳。","N5"],
["走る","hashiru","跑步","毎朝公園を走っています。","maiasa kouen o hashitte imasu.","每天早上在公園跑步。","N5"],
["歩く","aruku","走路","駅まで歩いて十分です。","eki made aruite juppun desu.","走路到車站十分鐘。","N5"],
["料理","ryouri","料理；做菜","料理をするのが好きです。","ryouri o suru no ga suki desu.","我喜歡做菜。","N5"],
["掃除","souji","打掃","週末に部屋を掃除する。","shuumatsu ni heya o souji suru.","週末打掃房間。","N5"],
["洗濯","sentaku","洗衣服","今日は洗濯をしました。","kyou wa sentaku o shimashita.","今天洗了衣服。","N5"],
["買い物","kaimono","購物","母と買い物に行きました。","haha to kaimono ni ikimashita.","和媽媽去買東西了。","N5"],
["服","fuku","衣服","新しい服が欲しいです。","atarashii fuku ga hoshii desu.","想要新衣服。","N5"],
["靴","kutsu","鞋子","この靴を履いてみてもいいですか。","kono kutsu o haite mite mo ii desu ka.","可以試穿這雙鞋嗎？","N5"],
["傘","kasa","傘","傘を持っていったほうがいいよ。","kasa o motte itta hou ga ii yo.","最好帶把傘喔。","N5"],
["財布","saifu","錢包","財布をなくしました。","saifu o nakushimashita.","我的錢包不見了。","N4"],
["鍵","kagi","鑰匙","鍵をどこに置いたか忘れた。","kagi o doko ni oita ka wasureta.","忘了鑰匙放哪了。","N4"],
["眼鏡","megane","眼鏡","眼鏡をかけている人が兄です。","megane o kakete iru hito ga ani desu.","戴眼鏡的是我哥。","N4"],
["色","iro","顏色","何色が好きですか。","naniiro ga suki desu ka.","你喜歡什麼顏色？","N5"],
["白い","shiroi","白色的","白いシャツを着ています。","shiroi shatsu o kite imasu.","穿著白襯衫。","N5"],
["黒い","kuroi","黑色的","黒いかばんはいくらですか。","kuroi kaban wa ikura desu ka.","黑色的包包多少錢？","N5"],
["赤い","akai","紅色的","赤いりんごを三つください。","akai ringo o mittsu kudasai.","請給我三顆紅蘋果。","N5"],
["青い","aoi","藍色的","空がとても青いですね。","sora ga totemo aoi desu ne.","天空好藍啊。","N5"],
["月曜日","getsuyoubi","星期一","月曜日から仕事です。","getsuyoubi kara shigoto desu.","星期一開始上班。","N5"],
["火曜日","kayoubi","星期二","火曜日は会議があります。","kayoubi wa kaigi ga arimasu.","星期二有會議。","N5"],
["水曜日","suiyoubi","星期三","水曜日に映画を見に行く。","suiyoubi ni eiga o mi ni iku.","星期三去看電影。","N5"],
["木曜日","mokuyoubi","星期四","木曜日は忙しいです。","mokuyoubi wa isogashii desu.","星期四很忙。","N5"],
["金曜日","kinyoubi","星期五","金曜日の夜は飲みに行こう。","kinyoubi no yoru wa nomi ni ikou.","星期五晚上去喝一杯吧。","N5"],
["土曜日","doyoubi","星期六","土曜日は買い物に行きます。","doyoubi wa kaimono ni ikimasu.","星期六去購物。","N5"],
["日曜日","nichiyoubi","星期日","日曜日は家でゆっくりする。","nichiyoubi wa ie de yukkuri suru.","星期日在家放鬆。","N5"],
["春","haru","春天","春に桜が咲きます。","haru ni sakura ga sakimasu.","春天櫻花會開。","N5"],
["夏","natsu","夏天","夏は花火大会があります。","natsu wa hanabi taikai ga arimasu.","夏天有煙火大會。","N5"],
["秋","aki","秋天","秋は紅葉がきれいです。","aki wa kouyou ga kirei desu.","秋天楓葉很美。","N5"],
["冬","fuyu","冬天","冬は雪が降ります。","fuyu wa yuki ga furimasu.","冬天會下雪。","N5"],
["雪","yuki","雪","初めて雪を見ました。","hajimete yuki o mimashita.","第一次看到雪。","N5"],
["風","kaze","風","今日は風が強いですね。","kyou wa kaze ga tsuyoi desu ne.","今天風好大。","N5"],
["風邪","kaze","感冒","風邪をひきました。","kaze o hikimashita.","我感冒了。","N5"],
["熱","netsu","發燒","熱があるので休みます。","netsu ga aru node yasumimasu.","發燒了所以請假。","N5"],
["頭","atama","頭","頭が痛いです。","atama ga itai desu.","頭痛。","N5"],
["お腹","onaka","肚子","お腹がいっぱいです。","onaka ga ippai desu.","肚子好飽。","N5"],
["目","me","眼睛","目が疲れました。","me ga tsukaremashita.","眼睛好累。","N5"],
["手","te","手","手を洗ってください。","te o aratte kudasai.","請洗手。","N5"],
["足","ashi","腳；腿","足が痛くて歩けません。","ashi ga itakute arukemasen.","腳痛走不動。","N5"],
["お母さん","okaasan","媽媽","お母さんに電話しました。","okaasan ni denwa shimashita.","打了電話給媽媽。","N5"],
["お父さん","otousan","爸爸","お父さんは今仕事中です。","otousan wa ima shigotochuu desu.","爸爸現在在工作。","N5"],
["子供","kodomo","小孩","子供が二人います。","kodomo ga futari imasu.","我有兩個小孩。","N5"],
["犬","inu","狗","犬を飼っています。","inu o katte imasu.","我有養狗。","N5"],
["猫","neko","貓","猫が好きですか、犬が好きですか。","neko ga suki desu ka, inu ga suki desu ka.","你喜歡貓還是狗？","N5"],
["先生","sensei","老師","先生に質問があります。","sensei ni shitsumon ga arimasu.","我有問題想問老師。","N5"],
["学生","gakusei","學生","大学の学生です。","daigaku no gakusei desu.","我是大學生。","N5"],
["質問","shitsumon","問題；提問","質問してもいいですか。","shitsumon shite mo ii desu ka.","可以提問嗎？","N5"],
["答える","kotaeru","回答","質問に答えてください。","shitsumon ni kotaete kudasai.","請回答問題。","N4"],
["意味","imi","意思","この言葉の意味は何ですか。","kono kotoba no imi wa nan desu ka.","這個詞是什麼意思？","N5"],
["言葉","kotoba","詞語；語言","新しい言葉を習いました。","atarashii kotoba o naraimashita.","學了新的詞。","N5"],
["英語","eigo","英語","英語で話してもいいですか。","eigo de hanashite mo ii desu ka.","可以用英語說嗎？","N5"],
["日本語","nihongo","日語","日本語を勉強しています。","nihongo o benkyou shite imasu.","我在學日語。","N5"],
["難しい","muzukashii","困難","漢字は難しいですが、面白いです。","kanji wa muzukashii desu ga, omoshiroi desu.","漢字很難但很有趣。","N5"],
["簡単","kantan","簡單","このテストは簡単でした。","kono tesuto wa kantan deshita.","這次考試很簡單。","N5"],
["面白い","omoshiroi","有趣","その話はとても面白いですね。","sono hanashi wa totemo omoshiroi desu ne.","那件事真有趣。","N5"],
["きれい","kirei","漂亮；乾淨","景色がきれいですね。","keshiki ga kirei desu ne.","風景好美啊。","N5"],
["かわいい","kawaii","可愛","この猫、かわいい！","kono neko, kawaii!","這隻貓好可愛！","N5"],
["すごい","sugoi","厲害；很棒","すごい！よくできたね。","sugoi! yoku dekita ne.","好厲害！做得真好。","N5"],
["上手","jouzu","擅長","日本語が上手ですね。","nihongo ga jouzu desu ne.","你的日語真好。","N5"],
["下手","heta","不擅長","歌は下手ですが、好きです。","uta wa heta desu ga, suki desu.","唱歌不好聽但我喜歡唱。","N5"],
["頑張る","ganbaru","加油；努力","明日も頑張ります。","ashita mo ganbarimasu.","明天也會加油。","N4"],
["心配","shinpai","擔心","心配しないでください。","shinpai shinaide kudasai.","請不要擔心。","N4"],
["嬉しい","ureshii","高興","会えて嬉しいです。","aete ureshii desu.","很高興見到你。","N4"],
["悲しい","kanashii","悲傷","その映画はとても悲しかった。","sono eiga wa totemo kanashikatta.","那部電影很悲傷。","N4"],
["眠い","nemui","想睡","今日はとても眠いです。","kyou wa totemo nemui desu.","今天好睏。","N4"],
["暇","hima","空閒","週末は暇ですか。","shuumatsu wa hima desu ka.","週末有空嗎？","N5"],
["便利","benri","方便","このアプリはとても便利です。","kono apuri wa totemo benri desu.","這個APP非常方便。","N5"],
["有名","yuumei","有名","ここは有名な観光地です。","koko wa yuumei na kankouchi desu.","這裡是有名的觀光景點。","N5"],
["大切","taisetsu","重要；珍惜","家族が一番大切です。","kazoku ga ichiban taisetsu desu.","家人最重要。","N4"],
["危ない","abunai","危險","危ない！車が来る！","abunai! kuruma ga kuru!","危險！車來了！","N5"],
["車","kuruma","車","車で行きましょう。","kuruma de ikimashou.","開車去吧。","N5"],
["自転車","jitensha","腳踏車","自転車で通勤しています。","jitensha de tsuukin shite imasu.","騎腳踏車通勤。","N5"],
["道","michi","路","道に迷いました。","michi ni mayoimashita.","我迷路了。","N5"],
["橋","hashi","橋","橋を渡ると公園があります。","hashi o wataru to kouen ga arimasu.","過橋就有公園。","N5"],
["公園","kouen","公園","公園でお弁当を食べよう。","kouen de obentou o tabeyou.","在公園吃便當吧。","N5"],
["銀行","ginkou","銀行","銀行は何時まで開いていますか。","ginkou wa nanji made aite imasu ka.","銀行開到幾點？","N5"],
["郵便局","yuubinkyoku","郵局","郵便局で切手を買います。","yuubinkyoku de kitte o kaimasu.","在郵局買郵票。","N5"],
["図書館","toshokan","圖書館","図書館で本を借りました。","toshokan de hon o karimashita.","在圖書館借了書。","N5"],
["海","umi","海","夏休みに海へ行きたい。","natsuyasumi ni umi e ikitai.","暑假想去海邊。","N5"],
["山","yama","山","週末に山に登ります。","shuumatsu ni yama ni noborimasu.","週末去爬山。","N5"],
["川","kawa","河川","川で魚を釣りました。","kawa de sakana o tsurimashita.","在河邊釣了魚。","N5"],
["空","sora","天空","空に虹が出ています。","sora ni niji ga dete imasu.","天空出現了彩虹。","N5"],
["月","tsuki","月亮；月份","今夜は月がきれいですね。","konya wa tsuki ga kirei desu ne.","今晚月色真美。","N5"],
["星","hoshi","星星","田舎では星がよく見えます。","inaka de wa hoshi ga yoku miemasu.","在鄉下星星看得很清楚。","N5"],
["花","hana","花","花見に行きましょう。","hanami ni ikimashou.","去賞花吧。","N5"],
["木","ki","樹","庭に大きな木があります。","niwa ni ookina ki ga arimasu.","院子裡有棵大樹。","N5"],
["開ける","akeru","打開","窓を開けてください。","mado o akete kudasai.","請打開窗戶。","N5"],
["閉める","shimeru","關閉","ドアを閉めるのを忘れた。","doa o shimeru no o wasureta.","忘了關門。","N5"],
["入る","hairu","進入","どうぞ、入ってください。","douzo, haitte kudasai.","請進。","N5"],
["出る","deru","出去；離開","家を八時に出ます。","ie o hachiji ni demasu.","八點出門。","N5"],
["座る","suwaru","坐","どうぞ、座ってください。","douzo, suwatte kudasai.","請坐。","N5"],
["立つ","tatsu","站","ずっと立っていて疲れた。","zutto tatte ite tsukareta.","一直站著好累。","N5"],
["持つ","motsu","拿；持有","荷物を持ちましょうか。","nimotsu o mochimashou ka.","要幫你拿行李嗎？","N5"],
["置く","oku","放置","かばんはここに置いてください。","kaban wa koko ni oite kudasai.","包包請放這裡。","N5"],
["借りる","kariru","借入","ペンを借りてもいいですか。","pen o karite mo ii desu ka.","可以借支筆嗎？","N5"],
["貸す","kasu","借出","傘を貸してくれてありがとう。","kasa o kashite kurete arigatou.","謝謝你借我傘。","N5"],
["送る","okuru","寄送；送行","メールを送りました。","meeru o okurimashita.","寄了郵件。","N4"],
["届く","todoku","送達","荷物が届きました。","nimotsu ga todokimashita.","包裹到了。","N4"],
["選ぶ","erabu","選擇","好きなものを選んでください。","suki na mono o erande kudasai.","請選你喜歡的。","N4"],
["決める","kimeru","決定","行き先を決めましたか。","ikisaki o kimemashita ka.","決定好目的地了嗎？","N4"],
["始まる","hajimaru","開始","会議は十時に始まります。","kaigi wa juuji ni hajimarimasu.","會議十點開始。","N5"],
["終わる","owaru","結束","授業は五時に終わります。","jugyou wa goji ni owarimasu.","課五點結束。","N5"],
["急ぐ","isogu","趕快","急がないと遅れますよ。","isoganai to okuremasu yo.","不快點會遲到喔。","N4"],
["遅れる","okureru","遲到","電車が遅れています。","densha ga okurete imasu.","電車誤點了。","N4"],
["間に合う","maniau","來得及","急げばまだ間に合う。","isogeba mada maniau.","快一點還來得及。","N4"],
["手伝う","tetsudau","幫忙","ちょっと手伝ってくれる？","chotto tetsudatte kureru?","可以幫我一下嗎？","N4"],
["頼む","tanomu","拜託；請求","友達に頼みました。","tomodachi ni tanomimashita.","拜託了朋友。","N4"],
["探す","sagasu","尋找","仕事を探しています。","shigoto o sagashite imasu.","正在找工作。","N4"],
["見つける","mitsukeru","找到","いい店を見つけました。","ii mise o mitsukemashita.","找到了一家好店。","N4"],
["なくす","nakusu","弄丟","パスポートをなくしました。","pasupooto o nakushimashita.","護照弄丟了。","N4"],
["会議","kaigi","會議","午後から会議があります。","gogo kara kaigi ga arimasu.","下午有會議。","N4"],
["連絡","renraku","聯絡","また連絡します。","mata renraku shimasu.","我再跟你聯絡。","N4"],
["約束","yakusoku","約定","友達と約束があります。","tomodachi to yakusoku ga arimasu.","和朋友有約。","N4"],
["用事","youji","要事","今日は用事があるので帰ります。","kyou wa youji ga aru node kaerimasu.","今天有事先回去了。","N4"],
["都合","tsugou","方便（時間）","明日の都合はどうですか。","ashita no tsugou wa dou desu ka.","明天方便嗎？","N4"],
["予定","yotei","預定；計畫","週末の予定はありますか。","shuumatsu no yotei wa arimasu ka.","週末有計畫嗎？","N4"],
["準備","junbi","準備","旅行の準備をしています。","ryokou no junbi o shite imasu.","正在準備旅行。","N4"],
["最近","saikin","最近","最近どうですか。","saikin dou desu ka.","最近怎麼樣？","N4"],
["久しぶり","hisashiburi","好久不見","久しぶり！元気だった？","hisashiburi! genki datta?","好久不見！過得好嗎？","N4"],
["お疲れ様","otsukaresama","辛苦了","お疲れ様でした。","otsukaresama deshita.","辛苦了。","N4"],
["よろしく","yoroshiku","請多指教","よろしくお願いします。","yoroshiku onegai shimasu.","請多多指教。","N5"],
["気をつける","ki o tsukeru","小心","帰り道、気をつけてね。","kaerimichi, ki o tsukete ne.","回家路上小心喔。","N4"],
["楽しみ","tanoshimi","期待","旅行が楽しみです。","ryokou ga tanoshimi desu.","很期待旅行。","N4"],
["残念","zannen","可惜；遺憾","行けなくて残念です。","ikenakute zannen desu.","不能去真可惜。","N4"],
["本当","hontou","真的","本当ですか。","hontou desu ka.","真的嗎？","N5"],
["もちろん","mochiron","當然","もちろん、いいですよ。","mochiron, ii desu yo.","當然可以呀。","N4"],
["絶対","zettai","絕對","絶対に忘れないでね。","zettai ni wasurenaide ne.","絕對不要忘記喔。","N4"],
["全部","zenbu","全部","全部でいくらですか。","zenbu de ikura desu ka.","總共多少錢？","N5"],
["半分","hanbun","一半","ケーキを半分に切ってください。","keeki o hanbun ni kitte kudasai.","請把蛋糕切一半。","N4"],
["もっと","motto","更加","もっと練習が必要です。","motto renshuu ga hitsuyou desu.","需要更多練習。","N5"],
["一番","ichiban","最；第一","何が一番好きですか。","nani ga ichiban suki desu ka.","你最喜歡什麼？","N5"],
["次","tsugi","下一個","次の駅で降ります。","tsugi no eki de orimasu.","下一站下車。","N5"],
["最初","saisho","最初","最初からもう一度やりましょう。","saisho kara mou ichido yarimashou.","從頭再來一次吧。","N4"],
["最後","saigo","最後","最後まで頑張ります。","saigo made ganbarimasu.","會努力到最後。","N4"],
["練習","renshuu","練習","毎日発音を練習しています。","mainichi hatsuon o renshuu shite imasu.","每天練習發音。","N4"],
["試験","shiken","考試","来週試験があります。","raishuu shiken ga arimasu.","下週有考試。","N4"],
["合格","goukaku","合格；考上","試験に合格しました！","shiken ni goukaku shimashita!","考試通過了！","N4"],
["経験","keiken","經驗","いい経験になりました。","ii keiken ni narimashita.","成為了很好的經驗。","N4"],
["夢","yume","夢想；夢","将来の夢は何ですか。","shourai no yume wa nan desu ka.","你將來的夢想是什麼？","N4"],
];

const WORDS_EN = [
["hello","/həˈloʊ/","你好","Hello! It's nice to meet you.","你好！很高興認識你。","A1"],
["thanks","/θæŋks/","謝謝","Thanks for your help today.","謝謝你今天的幫忙。","A1"],
["sorry","/ˈsɑːri/","對不起","Sorry, I'm late again.","對不起，我又遲到了。","A1"],
["please","/pliːz/","請","Could you say that again, please?","可以請你再說一次嗎？","A1"],
["excuse me","/ɪkˈskjuːz miː/","不好意思","Excuse me, where is the restroom?","不好意思，洗手間在哪裡？","A1"],
["morning","/ˈmɔːrnɪŋ/","早上","I go running every morning.","我每天早上跑步。","A1"],
["today","/təˈdeɪ/","今天","What are you doing today?","你今天要做什麼？","A1"],
["tomorrow","/təˈmɑːroʊ/","明天","See you tomorrow at nine.","明天九點見。","A1"],
["yesterday","/ˈjestərdeɪ/","昨天","I was really busy yesterday.","我昨天真的很忙。","A1"],
["now","/naʊ/","現在","I have to go now.","我現在得走了。","A1"],
["time","/taɪm/","時間","What time is it now?","現在幾點了？","A1"],
["eat","/iːt/","吃","Let's eat lunch together.","一起吃午餐吧。","A1"],
["drink","/drɪŋk/","喝","Would you like something to drink?","你想喝點什麼嗎？","A1"],
["go","/ɡoʊ/","去","I go to work by bus.","我搭公車上班。","A1"],
["come","/kʌm/","來","Can you come to my party?","你能來我的派對嗎？","A1"],
["see","/siː/","看見","Did you see my keys anywhere?","你有看到我的鑰匙嗎？","A1"],
["know","/noʊ/","知道","I don't know the answer.","我不知道答案。","A1"],
["think","/θɪŋk/","想；認為","I think it's a great idea.","我覺得這是個好主意。","A1"],
["want","/wɑːnt/","想要","I want to learn English.","我想學英文。","A1"],
["need","/niːd/","需要","Do you need any help?","你需要幫忙嗎？","A1"],
["like","/laɪk/","喜歡","I really like this song.","我真的很喜歡這首歌。","A1"],
["make","/meɪk/","做；製作","I'll make dinner tonight.","今晚我來做晚餐。","A1"],
["work","/wɜːrk/","工作","I work from home on Fridays.","我星期五在家工作。","A1"],
["home","/hoʊm/","家","I stayed home all weekend.","我整個週末都待在家。","A1"],
["family","/ˈfæməli/","家人","How is your family doing?","你的家人好嗎？","A1"],
["friend","/frend/","朋友","She's my best friend.","她是我最好的朋友。","A1"],
["money","/ˈmʌni/","錢","I need to save more money.","我需要多存點錢。","A1"],
["water","/ˈwɔːtər/","水","Can I have a glass of water?","可以給我一杯水嗎？","A1"],
["food","/fuːd/","食物","The food here is amazing.","這裡的食物很棒。","A1"],
["good","/ɡʊd/","好的","That's a good question.","那是個好問題。","A1"],
["bad","/bæd/","壞的","The weather was bad yesterday.","昨天天氣很糟。","A1"],
["big","/bɪɡ/","大的","They live in a big house.","他們住在一間大房子裡。","A1"],
["small","/smɔːl/","小的","Can I get a small coffee?","可以給我一杯小杯咖啡嗎？","A1"],
["new","/nuː/","新的","I got a new phone last week.","我上週買了新手機。","A1"],
["old","/oʊld/","舊的；老的","This is an old photo of us.","這是我們的舊照片。","A1"],
["happy","/ˈhæpi/","快樂的","I'm so happy to see you!","見到你我好開心！","A1"],
["tired","/ˈtaɪərd/","累的","I'm too tired to cook tonight.","我今晚累得不想煮飯。","A1"],
["hungry","/ˈhʌŋɡri/","餓的","I'm hungry. Let's get lunch.","我餓了，去吃午餐吧。","A1"],
["hot","/hɑːt/","熱的","It's really hot today.","今天真的很熱。","A1"],
["cold","/koʊld/","冷的","It gets cold at night here.","這裡晚上會變冷。","A1"],
["where","/wer/","哪裡","Where do you live?","你住在哪裡？","A1"],
["when","/wen/","什麼時候","When does the movie start?","電影什麼時候開始？","A1"],
["what","/wʌt/","什麼","What do you do for work?","你是做什麼工作的？","A1"],
["who","/huː/","誰","Who is that over there?","那邊那位是誰？","A1"],
["why","/waɪ/","為什麼","Why are you laughing?","你為什麼在笑？","A1"],
["how","/haʊ/","如何","How do I get to the station?","車站要怎麼去？","A1"],
["how much","/haʊ mʌtʃ/","多少錢","How much is this jacket?","這件外套多少錢？","A1"],
["help","/help/","幫助","Could you help me with this?","可以幫我弄這個嗎？","A1"],
["buy","/baɪ/","買","I want to buy some souvenirs.","我想買些紀念品。","A1"],
["give","/ɡɪv/","給","Give me a call later.","晚點打電話給我。","A1"],
["take","/teɪk/","拿；搭乘","I take the train to work.","我搭火車上班。","A1"],
["find","/faɪnd/","找到","I can't find my wallet.","我找不到我的錢包。","A1"],
["wait","/weɪt/","等待","Please wait a moment.","請稍等一下。","A1"],
["call","/kɔːl/","打電話","I'll call you tonight.","我今晚打給你。","A1"],
["talk","/tɔːk/","談話","Can we talk for a minute?","我們能談一下嗎？","A1"],
["ask","/æsk/","問","Can I ask you a question?","我可以問你一個問題嗎？","A1"],
["tell","/tel/","告訴","Tell me about your trip.","跟我說說你的旅行。","A1"],
["say","/seɪ/","說","What did you say?","你剛剛說什麼？","A1"],
["understand","/ˌʌndərˈstænd/","理解","I don't understand this word.","我不懂這個字。","A1"],
["speak","/spiːk/","說（語言）","Do you speak English?","你會說英語嗎？","A1"],
["breakfast","/ˈbrekfəst/","早餐","I usually skip breakfast.","我通常不吃早餐。","A1"],
["lunch","/lʌntʃ/","午餐","Let's grab lunch at noon.","中午一起吃午餐吧。","A1"],
["dinner","/ˈdɪnər/","晚餐","We're having dinner at seven.","我們七點吃晚餐。","A1"],
["coffee","/ˈkɔːfi/","咖啡","I can't start my day without coffee.","沒有咖啡我無法開始一天。","A1"],
["tea","/tiː/","茶","Would you like some tea?","要來點茶嗎？","A1"],
["restaurant","/ˈrestrɑːnt/","餐廳","This restaurant is always crowded.","這家餐廳總是很多人。","A1"],
["menu","/ˈmenjuː/","菜單","Could we see the menu, please?","可以給我們看菜單嗎？","A1"],
["order","/ˈɔːrdər/","點餐；訂購","Are you ready to order?","準備好點餐了嗎？","A1"],
["bill","/bɪl/","帳單","Could we get the bill, please?","麻煩給我們帳單。","A1"],
["delicious","/dɪˈlɪʃəs/","美味的","This soup is delicious!","這湯太好喝了！","A1"],
["breakfast in bed","/ˈbrekfəst ɪn bed/","在床上吃早餐","He made her breakfast in bed.","他為她做了床上早餐。","A2"],
["reservation","/ˌrezərˈveɪʃn/","預約","I'd like to make a reservation for two.","我想預約兩位。","A2"],
["takeout","/ˈteɪkaʊt/","外帶","Let's just get takeout tonight.","今晚叫外帶就好。","A2"],
["school","/skuːl/","學校","The kids are at school now.","孩子們現在在學校。","A1"],
["office","/ˈɔːfɪs/","辦公室","I left my laptop at the office.","我把筆電忘在辦公室了。","A1"],
["meeting","/ˈmiːtɪŋ/","會議","I have a meeting at three.","我三點有個會議。","A1"],
["busy","/ˈbɪzi/","忙碌的","I'm busy this week, sorry.","抱歉，我這週很忙。","A1"],
["free","/friː/","有空的；免費的","Are you free this weekend?","你這週末有空嗎？","A1"],
["late","/leɪt/","遲的","Sorry, I'm running late.","抱歉，我會晚點到。","A1"],
["early","/ˈɜːrli/","早的","I woke up early this morning.","我今天早上很早起床。","A1"],
["weekend","/ˈwiːkend/","週末","What are your weekend plans?","你週末有什麼計畫？","A1"],
["holiday","/ˈhɑːlədeɪ/","假日","Monday is a public holiday.","星期一是國定假日。","A1"],
["weather","/ˈweðər/","天氣","The weather is lovely today.","今天天氣很好。","A1"],
["rain","/reɪn/","雨；下雨","It might rain this afternoon.","今天下午可能會下雨。","A1"],
["sunny","/ˈsʌni/","晴朗的","It's sunny and warm outside.","外面陽光普照又溫暖。","A1"],
["umbrella","/ʌmˈbrelə/","雨傘","Don't forget your umbrella.","別忘了帶傘。","A1"],
["train","/treɪn/","火車","The train leaves in ten minutes.","火車十分鐘後開。","A1"],
["bus","/bʌs/","公車","I missed the last bus.","我錯過了末班公車。","A1"],
["station","/ˈsteɪʃn/","車站","Meet me at the station.","在車站跟我碰面。","A1"],
["airport","/ˈerpɔːrt/","機場","We arrived at the airport early.","我們提早到了機場。","A1"],
["ticket","/ˈtɪkɪt/","票","I bought two tickets online.","我在網路上買了兩張票。","A1"],
["left","/left/","左邊","Turn left at the corner.","在轉角左轉。","A1"],
["right","/raɪt/","右邊；正確的","The bank is on your right.","銀行在你的右手邊。","A1"],
["near","/nɪr/","附近","Is there a pharmacy near here?","這附近有藥局嗎？","A1"],
["far","/fɑːr/","遠的","The hotel isn't far from here.","飯店離這裡不遠。","A1"],
["map","/mæp/","地圖","Let me check the map.","讓我看一下地圖。","A1"],
["street","/striːt/","街道","They live on the same street.","他們住在同一條街上。","A1"],
["shop","/ʃɑːp/","商店","That shop sells handmade gifts.","那家店賣手工禮品。","A1"],
["supermarket","/ˈsuːpərmɑːrkɪt/","超市","I'm going to the supermarket. Need anything?","我要去超市，需要什麼嗎？","A1"],
["expensive","/ɪkˈspensɪv/","昂貴的","This bag is too expensive.","這個包太貴了。","A1"],
["cheap","/tʃiːp/","便宜的","I found a cheap flight to Tokyo.","我找到去東京的便宜機票。","A1"],
["price","/praɪs/","價格","The price includes breakfast.","價格含早餐。","A1"],
["pay","/peɪ/","付款","Can I pay by card?","我可以刷卡嗎？","A1"],
["cash","/kæʃ/","現金","I only have cash on me.","我身上只有現金。","A1"],
["change","/tʃeɪndʒ/","零錢；改變","Keep the change.","不用找零了。","A1"],
["open","/ˈoʊpən/","開；營業","What time does the store open?","這家店幾點開門？","A1"],
["close","/kloʊz/","關；打烊","The museum closes at five.","博物館五點閉館。","A1"],
["clothes","/kloʊðz/","衣服","I need to buy some new clothes.","我需要買些新衣服。","A1"],
["shoes","/ʃuːz/","鞋子","These shoes are so comfortable.","這雙鞋好舒服。","A1"],
["try on","/traɪ ɑːn/","試穿","Can I try this on?","我可以試穿這件嗎？","A2"],
["size","/saɪz/","尺寸","Do you have this in a bigger size?","這個有大一號的嗎？","A1"],
["color","/ˈkʌlər/","顏色","What's your favorite color?","你最喜歡什麼顏色？","A1"],
["wallet","/ˈwɑːlɪt/","錢包","I lost my wallet on the train.","我在火車上弄丟了錢包。","A2"],
["key","/kiː/","鑰匙","I locked my keys inside the car.","我把鑰匙鎖在車裡了。","A1"],
["phone","/foʊn/","電話；手機","My phone battery is dying.","我手機快沒電了。","A1"],
["message","/ˈmesɪdʒ/","訊息","I'll send you a message later.","我晚點傳訊息給你。","A1"],
["email","/ˈiːmeɪl/","電子郵件","Did you get my email?","你收到我的郵件了嗎？","A1"],
["photo","/ˈfoʊtoʊ/","照片","Can you take a photo of us?","可以幫我們拍張照嗎？","A1"],
["internet","/ˈɪntərnet/","網路","The internet is down again.","網路又斷了。","A1"],
["computer","/kəmˈpjuːtər/","電腦","My computer is really slow today.","我的電腦今天好慢。","A1"],
["sleep","/sliːp/","睡覺","I didn't sleep well last night.","我昨晚沒睡好。","A1"],
["wake up","/weɪk ʌp/","醒來","I wake up at six every day.","我每天六點起床。","A1"],
["shower","/ˈʃaʊər/","淋浴","I take a shower every morning.","我每天早上沖澡。","A1"],
["clean","/kliːn/","打掃；乾淨的","I need to clean my room.","我需要打掃房間。","A1"],
["cook","/kʊk/","煮飯","My dad loves to cook.","我爸爸很愛做菜。","A1"],
["wash","/wɑːʃ/","洗","Wash your hands before dinner.","晚餐前先洗手。","A1"],
["laundry","/ˈlɔːndri/","洗衣服","I do laundry on Sundays.","我星期日洗衣服。","A2"],
["walk","/wɔːk/","走路；散步","Let's take a walk after dinner.","晚餐後去散個步吧。","A1"],
["run","/rʌn/","跑步","She runs five kilometers every day.","她每天跑五公里。","A1"],
["exercise","/ˈeksərsaɪz/","運動","I try to exercise three times a week.","我盡量一週運動三次。","A1"],
["swim","/swɪm/","游泳","Can you swim?","你會游泳嗎？","A1"],
["play","/pleɪ/","玩；演奏","The kids are playing outside.","孩子們在外面玩。","A1"],
["watch","/wɑːtʃ/","觀看","We watched a movie last night.","我們昨晚看了一部電影。","A1"],
["listen","/ˈlɪsn/","聽","I listen to music on my way to work.","我上班路上聽音樂。","A1"],
["read","/riːd/","閱讀","I read before bed every night.","我每晚睡前閱讀。","A1"],
["write","/raɪt/","寫","Write your name here, please.","請在這裡寫下你的名字。","A1"],
["learn","/lɜːrn/","學習","I'm learning Japanese too.","我也在學日語。","A1"],
["study","/ˈstʌdi/","讀書；研讀","She's studying for her exam.","她正在準備考試。","A1"],
["teach","/tiːtʃ/","教","He teaches math at a high school.","他在高中教數學。","A1"],
["remember","/rɪˈmembər/","記得","I can't remember his name.","我想不起他的名字。","A1"],
["forget","/fərˈɡet/","忘記","Don't forget to lock the door.","別忘了鎖門。","A1"],
["music","/ˈmjuːzɪk/","音樂","What kind of music do you like?","你喜歡哪種音樂？","A1"],
["movie","/ˈmuːvi/","電影","That movie made me cry.","那部電影讓我哭了。","A1"],
["game","/ɡeɪm/","遊戲；比賽","Do you want to play a game?","要不要玩個遊戲？","A1"],
["book","/bʊk/","書","I'm reading a really good book.","我正在讀一本很棒的書。","A1"],
["travel","/ˈtrævl/","旅行","I love to travel alone.","我喜歡一個人旅行。","A1"],
["trip","/trɪp/","旅程","How was your trip to Japan?","你的日本之旅如何？","A1"],
["hotel","/hoʊˈtel/","飯店","The hotel has a great view.","這家飯店視野很棒。","A1"],
["vacation","/veɪˈkeɪʃn/","假期","We're going on vacation next month.","我們下個月要去度假。","A2"],
["beach","/biːtʃ/","海灘","Let's spend the day at the beach.","我們去海灘玩一天吧。","A1"],
["mountain","/ˈmaʊntn/","山","We hiked up the mountain.","我們爬上了那座山。","A1"],
["park","/pɑːrk/","公園","The park is beautiful in spring.","這座公園春天很美。","A1"],
["hospital","/ˈhɑːspɪtl/","醫院","He's in the hospital for a checkup.","他在醫院做檢查。","A1"],
["doctor","/ˈdɑːktər/","醫生","You should see a doctor.","你應該去看醫生。","A1"],
["medicine","/ˈmedɪsn/","藥","Take this medicine after meals.","這個藥飯後吃。","A1"],
["sick","/sɪk/","生病的","I feel sick today.","我今天不太舒服。","A1"],
["headache","/ˈhedeɪk/","頭痛","I have a terrible headache.","我頭痛得厲害。","A2"],
["fever","/ˈfiːvər/","發燒","She has a slight fever.","她有點發燒。","A2"],
["catch a cold","/kætʃ ə koʊld/","感冒","I caught a cold last week.","我上週感冒了。","A1"],
["rest","/rest/","休息","You should get some rest.","你應該休息一下。","A1"],
["healthy","/ˈhelθi/","健康的","Eating vegetables keeps you healthy.","吃蔬菜讓你保持健康。","A1"],
["body","/ˈbɑːdi/","身體","Stretching is good for your body.","伸展對身體很好。","A1"],
["head","/hed/","頭","I hit my head on the door.","我的頭撞到門了。","A1"],
["hand","/hænd/","手","Raise your hand if you know.","知道的請舉手。","A1"],
["eye","/aɪ/","眼睛","My eyes are tired from the screen.","我的眼睛盯螢幕盯得好累。","A1"],
["mother","/ˈmʌðər/","母親","My mother calls me every Sunday.","我媽媽每週日打給我。","A1"],
["father","/ˈfɑːðər/","父親","My father taught me to drive.","我爸爸教我開車。","A1"],
["child","/tʃaɪld/","小孩","They have one child.","他們有一個小孩。","A1"],
["dog","/dɔːɡ/","狗","Our dog loves the park.","我們的狗最愛公園。","A1"],
["cat","/kæt/","貓","The cat is sleeping on the sofa.","貓在沙發上睡覺。","A1"],
["teacher","/ˈtiːtʃər/","老師","Our teacher is very patient.","我們的老師很有耐心。","A1"],
["student","/ˈstuːdnt/","學生","She's a university student.","她是大學生。","A1"],
["question","/ˈkwestʃən/","問題","That's a difficult question.","那是個難題。","A1"],
["answer","/ˈænsər/","回答；答案","Nobody knew the answer.","沒有人知道答案。","A1"],
["word","/wɜːrd/","單字","What does this word mean?","這個字是什麼意思？","A1"],
["mean","/miːn/","意思是","What do you mean exactly?","你到底是什麼意思？","A1"],
["English","/ˈɪŋɡlɪʃ/","英語","Her English is getting better.","她的英文越來越好了。","A1"],
["difficult","/ˈdɪfɪkəlt/","困難的","This grammar is difficult for me.","這個文法對我來說很難。","A1"],
["easy","/ˈiːzi/","簡單的","The test was easier than I expected.","考試比我預期的簡單。","A1"],
["interesting","/ˈɪntrəstɪŋ/","有趣的","That's an interesting idea.","那是個有趣的想法。","A1"],
["Monday","/ˈmʌndeɪ/","星期一","I hate Monday mornings.","我討厭星期一早上。","A1"],
["Friday","/ˈfraɪdeɪ/","星期五","Thank goodness it's Friday!","感謝老天今天是星期五！","A1"],
["Saturday","/ˈsætərdeɪ/","星期六","We're having a barbecue on Saturday.","我們星期六要烤肉。","A1"],
["Sunday","/ˈsʌndeɪ/","星期日","Sunday is my lazy day.","星期日是我的耍廢日。","A1"],
["week","/wiːk/","星期；週","See you next week!","下週見！","A1"],
["month","/mʌnθ/","月","I'm moving next month.","我下個月要搬家。","A1"],
["year","/jɪr/","年","Happy New Year!","新年快樂！","A1"],
["birthday","/ˈbɜːrθdeɪ/","生日","Happy birthday! This is for you.","生日快樂！這是給你的。","A1"],
["gift","/ɡɪft/","禮物","I'm looking for a gift for my mom.","我在找送媽媽的禮物。","A1"],
["party","/ˈpɑːrti/","派對","Are you coming to the party?","你會來派對嗎？","A1"],
["invite","/ɪnˈvaɪt/","邀請","They invited us to dinner.","他們邀請我們吃晚餐。","A2"],
["congratulations","/kənˌɡrætʃəˈleɪʃnz/","恭喜","Congratulations on your new job!","恭喜你找到新工作！","A2"],
["spring","/sprɪŋ/","春天","The flowers bloom in spring.","春天百花盛開。","A1"],
["summer","/ˈsʌmər/","夏天","We swim a lot in summer.","我們夏天常游泳。","A1"],
["fall","/fɔːl/","秋天；掉落","The leaves turn red in fall.","秋天樹葉轉紅。","A1"],
["winter","/ˈwɪntər/","冬天","Winter here is very mild.","這裡的冬天很溫和。","A1"],
["snow","/snoʊ/","雪","It snowed all night.","下了一整夜的雪。","A1"],
["wind","/wɪnd/","風","The wind is strong today.","今天風很大。","A1"],
["beautiful","/ˈbjuːtɪfl/","美麗的","What a beautiful sunset!","多美的夕陽啊！","A1"],
["cute","/kjuːt/","可愛的","Your puppy is so cute!","你的小狗好可愛！","A1"],
["great","/ɡreɪt/","很棒的","That sounds great!","聽起來太棒了！","A1"],
["amazing","/əˈmeɪzɪŋ/","令人驚嘆的","The view from the top was amazing.","山頂的景色令人驚嘆。","A2"],
["important","/ɪmˈpɔːrtnt/","重要的","This meeting is very important.","這個會議非常重要。","A1"],
["dangerous","/ˈdeɪndʒərəs/","危險的","It's dangerous to text while driving.","開車傳訊息很危險。","A2"],
["careful","/ˈkerfl/","小心的","Be careful on the wet floor.","地板濕，小心走。","A1"],
["car","/kɑːr/","汽車","My car won't start.","我的車發不動。","A1"],
["bike","/baɪk/","腳踏車","I ride my bike to school.","我騎腳踏車上學。","A1"],
["road","/roʊd/","道路","This road is always busy.","這條路總是很塞。","A1"],
["bank","/bæŋk/","銀行","The bank closes at 3:30.","銀行三點半關門。","A1"],
["library","/ˈlaɪbreri/","圖書館","I borrowed three books from the library.","我從圖書館借了三本書。","A1"],
["sea","/siː/","海","Our room has a sea view.","我們的房間看得到海。","A1"],
["sky","/skaɪ/","天空","There isn't a cloud in the sky.","天空萬里無雲。","A1"],
["moon","/muːn/","月亮","The moon is full tonight.","今晚是滿月。","A1"],
["star","/stɑːr/","星星","You can see so many stars here.","這裡可以看到好多星星。","A1"],
["flower","/ˈflaʊər/","花","He gave me flowers on our anniversary.","他在紀念日送我花。","A1"],
["tree","/triː/","樹","We planted a tree in the yard.","我們在院子種了一棵樹。","A1"],
["door","/dɔːr/","門","Someone's knocking at the door.","有人在敲門。","A1"],
["window","/ˈwɪndoʊ/","窗戶","Could you open the window?","可以開一下窗嗎？","A1"],
["room","/ruːm/","房間","My room is a mess.","我的房間一團亂。","A1"],
["kitchen","/ˈkɪtʃɪn/","廚房","The kitchen smells wonderful.","廚房聞起來好香。","A1"],
["bathroom","/ˈbæθruːm/","浴室；廁所","The bathroom is down the hall.","浴室在走廊盡頭。","A1"],
["chair","/tʃer/","椅子","Pull up a chair and join us.","拉張椅子一起坐吧。","A1"],
["table","/ˈteɪbl/","桌子","I booked a table for four.","我訂了四人桌。","A1"],
["bed","/bed/","床","I just want to stay in bed.","我只想賴在床上。","A1"],
["begin","/bɪˈɡɪn/","開始","The class begins at nine.","課程九點開始。","A1"],
["finish","/ˈfɪnɪʃ/","完成","I finished the report early.","我提早完成了報告。","A1"],
["hurry","/ˈhɜːri/","趕快","Hurry up, or we'll miss the train!","快點，不然會錯過火車！","A2"],
["arrive","/əˈraɪv/","到達","What time does your flight arrive?","你的班機幾點到？","A1"],
["leave","/liːv/","離開","We should leave before dark.","我們該在天黑前離開。","A1"],
["meet","/miːt/","見面","Let's meet at the cafe at two.","兩點在咖啡廳見吧。","A1"],
["visit","/ˈvɪzɪt/","拜訪","We visited my grandparents last weekend.","我們上週末去看了祖父母。","A1"],
["stay","/steɪ/","停留；住","How long are you staying?","你要待多久？","A1"],
["move","/muːv/","搬家；移動","They moved to a new city.","他們搬到了新城市。","A1"],
["send","/send/","寄送","I sent the package this morning.","我今天早上寄了包裹。","A1"],
["receive","/rɪˈsiːv/","收到","Did you receive my letter?","你收到我的信了嗎？","A2"],
["choose","/tʃuːz/","選擇","It's hard to choose just one.","很難只選一個。","A1"],
["decide","/dɪˈsaɪd/","決定","Have you decided where to go?","你決定好去哪了嗎？","A2"],
["try","/traɪ/","嘗試","You should try the local food.","你應該試試當地美食。","A1"],
["use","/juːz/","使用","Can I use your charger?","可以借用你的充電器嗎？","A1"],
["borrow","/ˈbɑːroʊ/","借入","Can I borrow your pen?","可以借你的筆嗎？","A1"],
["lend","/lend/","借出","She lent me her umbrella.","她把傘借給我。","A2"],
["lose","/luːz/","丟失","I always lose my keys.","我老是弄丟鑰匙。","A1"],
["appointment","/əˈpɔɪntmənt/","預約（正式）","I have a dentist appointment at four.","我四點約了看牙醫。","A2"],
["schedule","/ˈskedʒuːl/","行程表","My schedule is full this week.","我這週行程滿檔。","A2"],
["plan","/plæn/","計畫","Do you have any plans tonight?","你今晚有什麼計畫嗎？","A1"],
["ready","/ˈredi/","準備好的","Are you ready to go?","你準備好要走了嗎？","A1"],
["prepare","/prɪˈper/","準備","I need to prepare for tomorrow's meeting.","我需要準備明天的會議。","A2"],
["recently","/ˈriːsntli/","最近","I've been really tired recently.","我最近一直很累。","A2"],
["always","/ˈɔːlweɪz/","總是","She always arrives on time.","她總是準時到。","A1"],
["sometimes","/ˈsʌmtaɪmz/","有時","Sometimes I work from a cafe.","有時我在咖啡廳工作。","A1"],
["usually","/ˈjuːʒuəli/","通常","I usually cook at home.","我通常在家煮飯。","A1"],
["never","/ˈnevər/","從不","I've never been to Europe.","我從沒去過歐洲。","A1"],
["together","/təˈɡeðər/","一起","We should have dinner together.","我們應該一起吃頓晚餐。","A1"],
["maybe","/ˈmeɪbi/","也許","Maybe we can go next week.","也許我們下週可以去。","A1"],
["of course","/əv kɔːrs/","當然","Of course you can join us!","你當然可以加入我們！","A1"],
["really","/ˈriːəli/","真的","Is that really true?","那是真的嗎？","A1"],
["actually","/ˈæktʃuəli/","其實","Actually, I've changed my mind.","其實，我改變主意了。","A2"],
["a lot","/ə lɑːt/","很多","Thanks a lot for everything.","非常感謝你做的一切。","A1"],
["a little","/ə ˈlɪtl/","一點點","I speak a little Japanese.","我會說一點日語。","A1"],
["too","/tuː/","太；也","This coffee is too sweet.","這咖啡太甜了。","A1"],
["very","/ˈveri/","非常","The movie was very good.","這部電影非常好看。","A1"],
["but","/bʌt/","但是","I want to go, but I'm busy.","我想去，但我很忙。","A1"],
["because","/bɪˈkɔːz/","因為","I stayed home because it rained.","因為下雨我待在家。","A1"],
["so","/soʊ/","所以","I was tired, so I went to bed early.","我很累，所以早早睡了。","A1"],
["first","/fɜːrst/","第一；首先","First, let me introduce myself.","首先，讓我自我介紹。","A1"],
["next","/nekst/","下一個","Get off at the next stop.","下一站下車。","A1"],
["last","/læst/","最後的；上一個","I saw him last Tuesday.","我上週二見過他。","A1"],
["favorite","/ˈfeɪvərɪt/","最喜歡的","This is my favorite cafe.","這是我最喜歡的咖啡廳。","A1"],
["best","/best/","最好的","This is the best pizza in town.","這是鎮上最好吃的披薩。","A1"],
["more","/mɔːr/","更多","Would you like some more?","要再來一點嗎？","A1"],
["enough","/ɪˈnʌf/","足夠的","We don't have enough time.","我們時間不夠。","A2"],
["all","/ɔːl/","全部","That's all for today.","今天就到這裡。","A1"],
["half","/hæf/","一半","I'll be there in half an hour.","我半小時後到。","A1"],
["practice","/ˈpræktɪs/","練習","Practice makes perfect.","熟能生巧。","A1"],
["exam","/ɪɡˈzæm/","考試","I passed the exam!","我通過考試了！","A2"],
["pass","/pæs/","通過；經過","She passed her driving test.","她通過了駕照考試。","A1"],
["fail","/feɪl/","失敗；不及格","Don't be afraid to fail.","不要害怕失敗。","A2"],
["experience","/ɪkˈspɪriəns/","經驗","It was an unforgettable experience.","那是難忘的經驗。","A2"],
["dream","/driːm/","夢想；夢","My dream is to live abroad.","我的夢想是住在國外。","A1"],
["job","/dʒɑːb/","工作","She found a new job.","她找到了新工作。","A1"],
["boss","/bɔːs/","老闆","My boss is pretty easygoing.","我老闆人很隨和。","A2"],
["colleague","/ˈkɑːliːɡ/","同事","I get along well with my colleagues.","我和同事處得很好。","B1"],
["salary","/ˈsæləri/","薪水","The salary is paid monthly.","薪水按月發放。","B1"],
["worry","/ˈwɜːri/","擔心","Don't worry about it.","別擔心那件事。","A1"],
["hope","/hoʊp/","希望","I hope you feel better soon.","希望你早日康復。","A1"],
["miss","/mɪs/","想念；錯過","I miss my hometown.","我想念我的家鄉。","A1"],
["surprised","/sərˈpraɪzd/","驚訝的","I was surprised by the news.","這消息讓我很驚訝。","A2"],
["excited","/ɪkˈsaɪtɪd/","興奮的","I'm so excited about the trip!","我對這趟旅行好興奮！","A1"],
["nervous","/ˈnɜːrvəs/","緊張的","I get nervous before interviews.","面試前我會緊張。","A2"],
["proud","/praʊd/","驕傲的","I'm proud of you.","我以你為榮。","A2"],
["kind","/kaɪnd/","親切的","Everyone here is so kind.","這裡的每個人都好親切。","A1"],
["funny","/ˈfʌni/","好笑的","He tells the funniest jokes.","他講的笑話最好笑。","A1"],
["quiet","/ˈkwaɪət/","安靜的","Please be quiet in the library.","在圖書館請保持安靜。","A1"],
["famous","/ˈfeɪməs/","有名的","This temple is famous for its garden.","這座寺廟以庭園聞名。","A1"],
["special","/ˈspeʃl/","特別的","Today is a special day.","今天是特別的日子。","A1"],
["same","/seɪm/","相同的","We have the same phone.","我們用同款手機。","A1"],
["different","/ˈdɪfrənt/","不同的","Let's try something different.","我們試試不一樣的吧。","A1"],
["problem","/ˈprɑːbləm/","問題","No problem at all.","完全沒問題。","A1"],
["idea","/aɪˈdiːə/","主意","That's a brilliant idea!","那真是個好主意！","A1"],
["fun","/fʌn/","樂趣；好玩","We had so much fun yesterday.","我們昨天玩得很開心。","A1"],
];
